addons:
  apt:
    packages:
      - python-pygments
cache: 
  directories:
    - /home/travis/bin
install:
  - mkdir /home/travis/bin && curl -LO https://github.com/gohugoio/hugo/releases/download/v0.45/hugo_0.45_Linux-64bit.tar.gz | tar zx && mv hugo /home/travis/bin
script:
  - /home/travis/bin/hugo
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
