baseurl = "https://ricedatasci.github.io/"
title = "Rice Data Science Club"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  description = "Official website of the Rice Data Science Club."
  #copyright = "&copy;2018 Your name or company"
  sidebarAbout = [
    "providing resources and skills to work with and understand data"
  ]
  email = "ricedatasci@gmail.com"

  # nav links in the side bar
  [[params.navlinks]]
  name = "home"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "about"
  url = "about/"

  [[params.navlinks]]
  name = "deep"
  url = "https://datasci.rice.edu/deep/"

  [[params.navlinks]]
  name = "events"
  url = "events/"

  [[params.navlinks]]
  name = "datathon"
  url = "datathon/"

  [[params.navlinks]]
  name = "calendar"
  url = "calendar/"

  [[params.navlinks]]
  name = "join"
  url = "join/"

  [params.social]
  github = "https://github.com/ricedatasci/"
  facebook = "https://www.facebook.com/groups/ricedatasci/"
  twitter = "https://twitter.com/ricedatasci"
  instagram = "https://instagram.com/ricedatasci"
